version: "3"
services:
  db:
    image: postgres:13
    container_name: db_my_chii_shop
    ports:
      - 6666:5432
    environment:
      POSTGRES_DB: mychiishop
      POSTGRES_USER: mychiishop
      POSTGRES_PASSWORD: VanBinh123
  server:
    depends_on:
      - db
    image: my_chii_shop_server
    container_name: my_chii_shop_server
    build:
      context: ./server
    restart: on-failure:5
    ports:
      - 1606:1606
    env_file: server/server.env
    volumes:
      - ./server:/usr/index
      - /usr/index/node_modules