version: "3"
services:
  db:
    image: postgres:13
    container_name: db_my_chii_shop
    ports:
      - 6666:5432
    environment:
      POSTGRES_DB: mychiishop
      POSTGRES_USER: mychiishop
      POSTGRES_PASSWORD: VanBinh123
  server:
    depends_on:
      - db
    image: main_server
    container_name: my_chii_server
    build:
      context: ./server
    command: >
     bash -c "knex migrate:latest --knexfile knexfile.js && npm run dev"
    restart: on-failure:5
    ports:
      - 1606:1606
      - 1417:1417
    env_file: server.env
    volumes:
      - ./server:/usr/app
      - ./server/node_modules:/usr/app/node_modules
      